--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: /__w/2/s/XmlToDatabase/build/../..//XmlToDatabase/db_values/init_scripts/MYSQL/mpRateValues.xml
--  Ran at: 8/24/21 4:10 AM
--  Against: null@offline:mysql?changeLogFile=changelogfile_mysql.csv
--  Liquibase version: 4.3.5
--  *********************************************************************

--  Changeset __w/2/s/XmlToDatabase/build/../../XmlToDatabase/db_values/init_scripts/MYSQL/mpRateValues.xml::1588925095097-1::generated
INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TRY', 'USD', '00001', 0.3508, NULL, 0, 0.3508, 1000, 0.3508, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TTD', 'USD', '00001', 0.19004, NULL, 0, 0.19004, 1, 0.19004, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TWD', 'USD', '00001', 0.0425, NULL, 0, 0.0425, 1, 0.0425, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TZS', 'USD', '00001', 0.00045, NULL, 0, 0.00045, 1, 0.00045, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SGD', 'USD', '00001', 1.2292, NULL, 0, 1.2292, 1, 1.2292, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ZAR', 'USD', '00001', 0.181, NULL, 0, 0.181, 1, 0.181, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KHR', 'USD', '00001', 0.0003, NULL, 0, 0.0003, 1, 0.0003, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'VND', 'USD', '00001', 0.00006, NULL, 0, 0.00006, 1, 0.00006, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'JEP', 'USD', '00001', 1.42739, NULL, 0, 1.42739, 1, 1.42739, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'UAH', 'USD', '00001', 0.0385, NULL, 0, 0.0385, 1, 0.0385, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'UGX', 'USD', '00001', 0.00029, NULL, 0, 0.00029, 1, 0.00029, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'UYU', 'USD', '00001', 0.0319, NULL, 0, 0.0319, 1, 0.0319, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'UZS', 'USD', '00001', 0.00034, NULL, 0, 0.00034, 1, 0.00034, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'VEF', 'USD', '00001', 0.1574, NULL, 0, 0.1574, 1, 0.1574, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'VUV', 'USD', '00001', 0.0091, NULL, 0, 0.0091, 1, 0.0091, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'WST', 'USD', '00001', 0.3912, NULL, 0, 0.3912, 1, 0.3912, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'XAF', 'USD', '00001', 0.0017, NULL, 0, 0.0017, 1, 0.0017, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'XCD', 'USD', '00001', 0.3703, NULL, 0, 0.3703, 1, 0.3703, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'XDR', 'USD', '00001', 1.4095, NULL, 0, 1.4095, 1, 1.4095, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'XOF', 'USD', '00001', 0.0017, NULL, 0, 0.0017, 1, 0.0017, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'XPF', 'USD', '00001', 0.0095, NULL, 0, 0.0095, 1, 0.0095, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'YER', 'USD', '00001', 0.0046, NULL, 0, 0.0046, 1, 0.0046, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ZMW', 'USD', '00001', 0.00009, NULL, 0, 0.00009, 1, 0.00009, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ZWD', 'USD', '00001', 0.0027, NULL, 0, 0.0027, 1, 0.0027, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ADP', 'USD', '00001', 0.0107, NULL, 0, 0.0107, 1, 0.0107, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AED', 'USD', '00001', 0.2722, NULL, 0, 0.2722, 1, 0.2722, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AFA', 'USD', '00001', 0.0259, NULL, 0, 0.0259, 1, 0.0259, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AFN', 'USD', '00001', 0.0144, NULL, 0, 0.0144, 1, 0.0144, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ALL', 'USD', '00001', 0.0081, NULL, 0, 0.0081, 1, 0.0081, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AMD', 'USD', '00001', 0.002, NULL, 0, 0.002, 1, 0.002, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ANG', 'USD', '00001', 0.5586, NULL, 0, 0.5586, 1, 0.5586, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AOA', 'USD', '00001', 0.0062, NULL, 0, 0.0062, 1, 0.0062, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ARS', 'USD', '00001', 0.1134, NULL, 0, 0.1134, 1, 0.1134, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AUD', 'USD', '00001', 0.7697, NULL, 0, 0.7697, 1, 0.7697, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AWG', 'USD', '00001', 0.5586, NULL, 0, 0.5586, 1, 0.5586, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'AZN', 'USD', '00001', 0.6591, NULL, 0, 0.6591, 1, 0.6591, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BAM', 'USD', '00001', 0.5831, NULL, 0, 0.5831, 1, 0.5831, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BBD', 'USD', '00001', 0.5, NULL, 0, 0.5, 1, 0.5, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BDT', 'USD', '00001', 0.0128, NULL, 0, 0.0128, 1, 0.0128, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BGL', 'USD', '00001', 0.9118, NULL, 0, 0.9118, 1, 0.9118, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BGN', 'USD', '00001', 0.5828, NULL, 0, 0.5828, 1, 0.5828, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BHD', 'USD', '00001', 2.6522, NULL, 0, 2.6522, 1, 2.6522, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BIF', 'USD', '00001', 0.0006, NULL, 0, 0.0006, 1, 0.0006, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BMD', 'USD', '00001', 0.8805, NULL, 0, 0.8805, 1, 0.8805, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BND', 'USD', '00001', 1, NULL, 0, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BOB', 'USD', '00001', 0.1446, NULL, 0, 0.1446, 1, 0.1446, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BRL', 'USD', '00001', 0.3077, NULL, 0, 0.3077, 1, 0.3077, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BSD', 'USD', '00001', 1, NULL, 0, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BTN', 'USD', '00001', 0.015, NULL, 0, 0.015, 1, 0.015, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BWP', 'USD', '00001', 0.091, NULL, 0, 0.091, 1, 0.091, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BYR', 'USD', '00001', 0.00004, NULL, 0, 0.00004, 1, 0.00004, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'BZD', 'USD', '00001', 0.5012, NULL, 0, 0.5012, 1, 0.5012, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CAD', 'USD', '00001', 0.7926, NULL, 0, 0.7926, 1, 0.7926, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CDF', 'USD', '00001', 0.001, NULL, 0, 0.001, 1, 0.001, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CHF', 'USD', '00001', 1.0373, NULL, 0, 1.0373, 1, 1.0373, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CLP', 'USD', '00001', 0.001605, NULL, 0, 0.001605, 1, 0.001605, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CNY', 'USD', '00001', 0.161, NULL, 0, 0.161, 1, 0.161, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'COP', 'USD', '00001', 0.0003, NULL, 0, 0.0003, 1, 0.0003, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CRC', 'USD', '00001', 0.0018, NULL, 0, 0.0018, 1, 0.0018, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CUC', 'USD', '00001', 1, NULL, 0, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CUP', 'USD', '00001', 0.0377, NULL, 0, 0.0377, 1, 0.0377, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CVE', 'USD', '00001', 0.0103, NULL, 0, 0.0103, 1, 0.0103, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'CZK', 'USD', '00001', 0.03947, NULL, 0, 0.03947, 1, 0.03947, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'DJF', 'USD', '00001', 0.0056, NULL, 0, 0.0056, 1, 0.0056, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'DKK', 'USD', '00001', 0.2387, NULL, 0, 0.2387, 1, 0.2387, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'DOP', 'USD', '00001', 0.0217, NULL, 0, 0.0217, 1, 0.0217, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'DZD', 'USD', '00001', 0.0092, NULL, 0, 0.0092, 1, 0.0092, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'EGP', 'USD', '00001', 0.1126, NULL, 0, 0.1126, 1, 0.1126, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ERN', 'USD', '00001', 0.0955, NULL, 0, 0.0955, 1, 0.0955, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ETB', 'USD', '00001', 0.0465, NULL, 0, 0.0465, 1, 0.0465, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'EUR', 'USD', '00001', 1.7808, NULL, 0, 1.7808, 1, 1.7808, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'FJD', 'USD', '00001', 0.4795, NULL, 0, 0.4795, 1, 0.4795, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'FKP', 'USD', '00001', 1.4133, NULL, 0, 1.4133, 1, 1.4133, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GBP', 'USD', '00001', 1.4133, NULL, 0, 1.4133, 1, 1.4133, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GEL', 'USD', '00001', 0.4367, NULL, 0, 0.4367, 1, 0.4367, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GHS', 'USD', '00001', 0.26, NULL, 0, 0.26, 1, 0.26, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GIP', 'USD', '00001', 1.415, NULL, 0, 1.415, 1, 1.415, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GMD', 'USD', '00001', 0.0235, NULL, 0, 0.0235, 1, 0.0235, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GNF', 'USD', '00001', 0.00013, NULL, 0, 0.00013, 1, 0.00013, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GTQ', 'USD', '00001', 0.1296, NULL, 0, 0.1296, 1, 0.1296, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GWP', 'USD', '00001', 0.011, NULL, 0, 0.011, 1, 0.011, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'GYD', 'USD', '00001', 0.0048, NULL, 0, 0.0048, 1, 0.0048, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'HKD', 'USD', '00001', 0.1579, NULL, 0, 0.1579, 1, 0.1579, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'HNL', 'USD', '00001', 0.0442, NULL, 0, 0.0442, 1, 0.0442, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'HRK', 'USD', '00001', 0.152, NULL, 0, 0.152, 1, 0.152, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'HTG', 'USD', '00001', 0.0162, NULL, 0, 0.0162, 1, 0.0162, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'HUF', 'USD', '00001', 0.0036, NULL, 0, 0.0036, 1, 0.0036, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'IDR', 'USD', '00001', 0.00014, NULL, 0, 0.00014, 100, 0.00014, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ILS', 'USD', '00001', 0.2621, NULL, 0, 0.2621, 1, 0.2621, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'IQD', 'USD', '00001', 0.0009, NULL, 0, 0.0009, 1, 0.0009, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'IRR', 'USD', '00001', 0.0001, NULL, 0, 0.0001, 10000, 0.0001, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'ISK', 'USD', '00001', 0.0081, NULL, 0, 0.0081, 1, 0.0081, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'INR', 'USD', '00001', 0.0272, NULL, 0, 0.0272, 1, 0.0272, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'JMD', 'USD', '00001', 0.0082, NULL, 0, 0.0082, 1, 0.0082, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'JOD', 'USD', '00001', 1.4114, NULL, 0, 1.4114, 1, 1.4114, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'JPY', 'USD', '00001', 0.0152, NULL, 0, 0.0152, 1, 0.0152, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KES', 'USD', '00001', 0.0098, NULL, 0, 0.0098, 1, 0.0098, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KGS', 'USD', '00001', 0.0144, NULL, 0, 0.0144, 1, 0.0144, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KMF', 'USD', '00001', 0.0023, NULL, 0, 0.0023, 1, 0.0023, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KPW', 'USD', '00001', 0.0076, NULL, 0, 0.0076, 1, 0.0076, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KRW', 'USD', '00001', 0.00115, NULL, 0, 0.00115, 1, 0.00115, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KWD', 'USD', '00001', 4.4739, NULL, 0, 4.4739, 1, 4.4739, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KYD', 'USD', '00001', 1.2195, NULL, 0, 1.2195, 1, 1.2195, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'KZT', 'USD', '00001', 0.0029, NULL, 0, 0.0029, 1, 0.0029, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LAK', 'USD', '00001', 0.00012, NULL, 0, 0.00012, 1, 0.00012, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LBP', 'USD', '00001', 0.00081, NULL, 0, 0.00081, 1, 0.00081, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LKR', 'USD', '00001', 0.0112, NULL, 0, 0.0112, 1, 0.0112, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LRD', 'USD', '00001', 0.0108, NULL, 0, 0.0108, 1, 0.0108, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LSL', 'USD', '00001', 0.0659, NULL, 0, 0.0659, 1, 0.0659, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LTL', 'USD', '00001', 0.3287, NULL, 0, 0.3287, 1, 0.3287, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LVL', 'USD', '00001', 1.6152, NULL, 0, 1.6152, 1, 1.6152, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'LYD', 'USD', '00001', 0.7347, NULL, 0, 0.7347, 1, 0.7347, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MAD', 'USD', '00001', 0.1548, NULL, 0, 0.1548, 1, 0.1548, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MDL', 'USD', '00001', 0.0509, NULL, 0, 0.0509, 1, 0.0509, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MGA', 'USD', '00001', 0.00031, NULL, 0, 0.00031, 1, 0.00031, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MKD', 'USD', '00001', 0.0184, NULL, 0, 0.0184, 1, 0.0184, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MMK', 'USD', '00001', 0.0008, NULL, 0, 0.0008, 1, 0.0008, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MNT', 'USD', '00001', 0.00049, NULL, 0, 0.00049, 1, 0.00049, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MOP', 'USD', '00001', 0.1251, NULL, 0, 0.1251, 1, 0.1251, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MRO', 'USD', '00001', 0.0032, NULL, 0, 0.0032, 1, 0.0032, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MTL', 'USD', '00001', 4.1482, NULL, 0, 4.1482, 1, 4.1482, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MUR', 'USD', '00001', 0.0418, NULL, 0, 0.0418, 1, 0.0418, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MVR', 'USD', '00001', 0.0651, NULL, 0, 0.0651, 1, 0.0651, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MWK', 'USD', '00001', 0.0014, NULL, 0, 0.0014, 1, 0.0014, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MXN', 'USD', '00001', 0.0563, NULL, 0, 0.0563, 1, 0.0563, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MYR', 'USD', '00001', 0.406, NULL, 0, 0.406, 1, 0.406, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'MZN', 'USD', '00001', 0.0198, NULL, 0, 0.0198, 1, 0.0198, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'NAD', 'USD', '00001', 0.0659, NULL, 0, 0.0659, 1, 0.0659, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'NGN', 'USD', '00001', 0.0079, NULL, 0, 0.0079, 100, 0.0079, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'NIO', 'USD', '00001', 0.0353, NULL, 0, 0.0353, 1, 0.0353, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'NOK', 'USD', '00001', 0.2285, NULL, 0, 0.2285, 1, 0.2285, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'NPR', 'USD', '00001', 0.0093, NULL, 0, 0.0093, 1, 0.0093, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'NZD', 'USD', '00001', 1.0178, NULL, 0, 1.0178, 1, 1.0178, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'OMR', 'USD', '00001', 3.1844, NULL, 0, 3.1844, 1, 3.1844, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PAB', 'USD', '00001', 1, NULL, 0, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PEN', 'USD', '00001', 0.2965, NULL, 0, 0.2965, 1, 0.2965, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PGK', 'USD', '00001', 0.325, NULL, 0, 0.325, 1, 0.325, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PHP', 'USD', '00001', 0.0282, NULL, 0, 0.0282, 1, 0.0282, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PKR', 'USD', '00001', 0.0145, NULL, 0, 0.0145, 1, 0.0145, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PLN', 'USD', '00001', 0.448, NULL, 0, 0.448, 1, 0.448, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'PYG', 'USD', '00001', 0.00018, NULL, 0, 0.00018, 1, 0.00018, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'QAR', 'USD', '00001', 0.3374, NULL, 0, 0.3374, 1, 0.3374, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'RON', 'USD', '00001', 0.254, NULL, 0, 0.254, 1, 0.254, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'RSD', 'USD', '00001', 0.0092, NULL, 0, 0.0092, 1, 0.0092, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'RUB', 'USD', '00001', 0.044, NULL, 0, 0.044, 1, 0.044, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'RWF', 'USD', '00001', 0.0012, NULL, 0, 0.0012, 1, 0.0012, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'RUR', 'USD', '00001', 0.2092, NULL, 0, 0.2092, 1, 0.2092, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SAR', 'USD', '00001', 0.3277, NULL, 0, 0.3277, 1, 0.3277, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SBD', 'USD', '00001', 0.1262, NULL, 0, 0.1262, 1, 0.1262, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SCR', 'USD', '00001', 0.0727, NULL, 0, 0.0727, 1, 0.0727, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SDG', 'USD', '00001', 0.1639, NULL, 0, 0.1639, 1, 0.1639, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SEK', 'USD', '00001', 0.1943, NULL, 0, 0.1943, 1, 0.1943, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SLL', 'USD', '00001', 0.00025, NULL, 0, 0.00025, 1, 0.00025, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SOS', 'USD', '00001', 0.00025, NULL, 0, 0.00025, 1, 0.00025, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SRD', 'USD', '00001', 0.1957, NULL, 0, 0.1957, 1, 0.1957, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'STD', 'USD', '00001', 0.000046, NULL, 0, 0.000046, 10000, 0.000046, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SVC', 'USD', '00001', 0.1142, NULL, 0, 0.1142, 1, 0.1142, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SZL', 'USD', '00001', 0.0656, NULL, 0, 0.0656, 1, 0.0656, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'USD', 'USD', '00001', 1, NULL, 0, 1, 1, 1, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SHP', 'USD', '00001', 1.9728, NULL, 0, 1.9728, 1, 1.9728, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'SYP', 'USD', '00001', 0.0253, NULL, 0, 0.0253, 1, 0.0253, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'THB', 'USD', '00001', 0.0399, NULL, 0, 0.0399, 1, 0.0399, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TJS', 'USD', '00001', 0.127, NULL, 0, 0.127, 1, 0.127, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TMT', 'USD', '00001', 0.2857, NULL, 0, 0.2857, 1, 0.2857, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TND', 'USD', '00001', 0.9001, NULL, 0, 0.9001, 1, 0.9001, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TOP', 'USD', '00001', 0.4538, NULL, 0, 0.4538, 1, 0.4538, NULL, NULL, NULL);

INSERT INTO GTP_XCH_RATES (BANK_ABBV_NAME, ISO_CODE, BASE_ISO_CODE, BRCH_CODE, BUY_TT_RATE, EURO_IN_CURRENCY, EURO_RATE, MID_TT_RATE, PATY_VAL, SELL_TT_RATE, UPDATE_DATE, START_VALUE_DATE, END_VALUE_DATE) VALUES ('*', 'TPE', 'USD', '00001', 0.1001, NULL, 0, 0.1001, 1, 0.1001, NULL, NULL, NULL);

