--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: /__w/2/s/XmlToDatabase/build/../..//XmlToDatabase/db_values/init_scripts/MYSQL/bankCurrencyValues.xml
--  Ran at: 8/24/21 4:10 AM
--  Against: null@offline:mysql?changeLogFile=changelogfile_mysql.csv
--  Liquibase version: 4.3.5
--  *********************************************************************

--  Changeset __w/2/s/XmlToDatabase/build/../../XmlToDatabase/db_values/init_scripts/MYSQL/bankCurrencyValues.xml::1588944315883-1::generated
INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ADP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AED');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AFA');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AFN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ALL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AMD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ANG');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AOA');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ARS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AUD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AWG');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'AZN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BAM');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BBD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BDT');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BGL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BGN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BHD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BIF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BMD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BND');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BOB');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BRL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BSD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BTN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BWP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BYR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'BZD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CAD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CDF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CHF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CLP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CNY');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'COP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CRC');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CUC');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CUP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CVE');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'CZK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'DJF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'DKK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'DOP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'DZD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'EGP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ERN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ETB');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'EUR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'FJD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'FKP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GBP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GEL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GHS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GIP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GMD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GNF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GTQ');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GWP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'GYD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'HKD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'HNL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'HRK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'HTG');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'HUF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'IDR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ILS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'INR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'IQD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'IRR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ISK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'JEP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'JMD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'JOD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'JPY');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KES');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KGS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KHR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KMF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KPW');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KRW');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KWD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KYD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'KZT');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LAK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LBP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LKR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LRD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LSL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LTL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LVL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'LYD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MAD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MDL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MGA');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MKD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MMK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MNT');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MOP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MRO');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MTL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MUR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MVR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MWK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MXN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MYR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'MZN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'NAD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'NGN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'NIO');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'NOK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'NPR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'NZD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'OMR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PAB');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PEN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PGK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PHP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PKR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PLN');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'PYG');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'QAR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'RON');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'RSD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'RUB');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'RUR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'RWF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SAR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SBD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SCR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SDG');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SEK');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SGD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SHP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SLL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SOS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SRD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'STD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SVC');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SYP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'SZL');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'THB');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TJS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TMT');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TND');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TOP');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TPE');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TRY');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TTD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TWD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'TZS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'UAH');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'UGX');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'USD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'UYU');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'UZS');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'VEF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'VND');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'VUV');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'WST');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'XAF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'XCD');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'XDR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'XOF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'XPF');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'YER');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ZAR');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ZMW');

INSERT INTO GTP_BANK_CURRENCY (BANK_ABBV_NAME, ISO_CODE) VALUES ('*', 'ZWD');

