--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: /__w/2/s/XmlToDatabase/build/../..//XmlToDatabase/db_values/init_scripts/MYSQL/psmlValues.xml
--  Ran at: 8/24/21 4:10 AM
--  Against: null@offline:mysql?changeLogFile=changelogfile_mysql.csv
--  Liquibase version: 4.3.5
--  *********************************************************************

--  Changeset __w/2/s/XmlToDatabase/build/../../XmlToDatabase/db_values/init_scripts/MYSQL/psmlValues.xml::1588944787709-1::generated
INSERT INTO GTP_USER_PROFILE (PSML_ID, COMPANY_NAME, COUNTRY, LANGUAGE, MEDIA_TYPE, PAGE, PROFILE, USER_NAME) VALUES (1, 'MISYSBANK', NULL, 'en', NULL, 'MisysBank_en.psml', '<?xml version="1.0" encoding="iso-8859-1"?><portlets user="default"><controller name="com.misys.portal.core.portal.controllers.CardPortletController"><parameter name="parameter" value="pane"/></controller><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"><parameter name="sizes" value="250,*"/><parameter name="mode" value="row"/></controller><layout position="0"/><metainfo><title>Home Page</title></metainfo><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"/><layout position="1"/><entry type="ref" parent="WelcomeAdmin_en"><control name="com.misys.portal.core.portal.controls.BorderPortletControl"/><layout position="0"/><parameter name="menu" value="true"/></entry><entry type="ref" parent="TradeApplicationsAdminPortlet"><layout position="1"/><parameter name="menu" value="true"/></entry><entry parent="BookmarkPortlet" type="ref"><parameter name="menu" value="true" /><metainfo><title>My Favorites</title><description>My Favorites</description></metainfo><layout position="2" size="NORMAL" /></entry></portlets><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"/><layout position="2"/><entry type="ref" parent="BankOngoingTasksList"><layout position="0"/></entry><entry type="ref" parent="TradeRecentApps"><parameter name="max_apps" value="10" type="int"/><layout position="1"/></entry><entry type="ref" parent="TradeRecentRequests"><parameter name="max_requests" value="10" type="int"/><layout position="2"/></entry><entry parent="PendingCounterpartiesActivationPortlet" type="ref"><parameter name="max_apps" value="10" /><layout position="3" size="NORMAL"/></entry></portlets></portlets></portlets>', NULL);

INSERT INTO GTP_USER_PROFILE (PSML_ID, COMPANY_NAME, COUNTRY, LANGUAGE, MEDIA_TYPE, PAGE, PROFILE, USER_NAME) VALUES (2, 'MISYSBANK', NULL, 'fr', NULL, 'MisysBank_fr.psml', '<?xml version="1.0" encoding="iso-8859-1"?><portlets user="default"><controller name="com.misys.portal.core.portal.controllers.CardPortletController"><parameter name="parameter" value="pane"/></controller><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"><parameter name="sizes" value="250,*"/><parameter name="mode" value="row"/></controller><layout position="0"/><metainfo><title>Home Page</title></metainfo><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"/><layout position="1"/><entry type="ref" parent="WelcomeAdmin_en"><control name="com.misys.portal.core.portal.controls.BorderPortletControl"/><layout position="0"/><parameter name="menu" value="true"/></entry><entry type="ref" parent="TradeApplicationsAdminPortlet"><layout position="1"/><parameter name="menu" value="true"/></entry><entry parent="BookmarkPortlet" type="ref"><parameter name="menu" value="true" /><metainfo><title>My Favorites</title><description>My Favorites</description></metainfo><layout position="2" size="NORMAL" /></entry></portlets><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"/><layout position="2"/><entry type="ref" parent="BankOngoingTasksList"><layout position="0"/></entry><entry type="ref" parent="TradeRecentApps"><parameter name="max_apps" value="10" type="int"/><layout position="1"/></entry><entry type="ref" parent="TradeRecentRequests"><parameter name="max_requests" value="10" type="int"/><layout position="2"/></entry><entry parent="PendingCounterpartiesActivationPortlet" type="ref"><parameter name="max_apps" value="10" /><layout position="3" size="NORMAL"/></entry></portlets></portlets></portlets>', NULL);

INSERT INTO GTP_USER_PROFILE (PSML_ID, COMPANY_NAME, COUNTRY, LANGUAGE, MEDIA_TYPE, PAGE, PROFILE, USER_NAME) VALUES (3, 'MISYSBANK', NULL, 'ar', NULL, 'MisysBank_ar.psml', '<?xml version="1.0" encoding="iso-8859-1"?><portlets user="default"><controller name="com.misys.portal.core.portal.controllers.CardPortletController"><parameter name="parameter" value="pane"/></controller><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"><parameter name="sizes" value="250,*"/><parameter name="mode" value="row"/></controller><layout position="0"/><metainfo><title>Home Page</title></metainfo><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"/><layout position="1"/><entry type="ref" parent="WelcomeAdmin_en"><control name="com.misys.portal.core.portal.controls.BorderPortletControl"/><layout position="0"/><parameter name="menu" value="true"/></entry><entry type="ref" parent="TradeApplicationsAdminPortlet"><layout position="1"/><parameter name="menu" value="true"/></entry><entry parent="BookmarkPortlet" type="ref"><parameter name="menu" value="true" /><metainfo><title>My Favorites</title><description>My Favorites</description></metainfo><layout position="2" size="NORMAL" /></entry></portlets><portlets><controller name="com.misys.portal.core.portal.controllers.RowColumnPortletController"/><layout position="2"/><entry type="ref" parent="BankOngoingTasksList"><layout position="0"/></entry><entry type="ref" parent="TradeRecentApps"><parameter name="max_apps" value="10" type="int"/><layout position="1"/></entry><entry type="ref" parent="TradeRecentRequests"><parameter name="max_requests" value="10" type="int"/><layout position="2"/></entry><entry parent="PendingCounterpartiesActivationPortlet" type="ref"><parameter name="max_apps" value="10" /><layout position="3" size="NORMAL"/></entry></portlets></portlets></portlets>', NULL);

