apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftboracle
  labels:
    app: ftbjbossoracle
spec:
  replicas: 1
  serviceName: ftboraclesvc
  selector:
    matchLabels:
      app: ftbjbossoracle
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ftbjbossoracle
    spec:
      #securityContext:
      #  runAsUser: 54321
      #  fsGroup: 54321
      #nodeSelector:
      #  kubernetes.io/hostname: aks-l21d11107014-59385960-vmss00007u
      containers:
      - name: ftboraclecontainer
        image: p32q22702680001.azurecr.io/devops/oracle/database:19.3.0-ee
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 3603Mi
        #  limits:
        #    cpu: 250m
        #    memory: 3603Mi
        volumeMounts:

        - name: ftb-oracledb-config
          mountPath: /opt/oracle/oradata
        # command: ["ping"]
        # args: ["localhost"]
        # image: p32q22702680001.azurecr.io/devops/oracle:blank_schema
        imagePullPolicy: IfNotPresent
        # env:
        #   - name: ORACLE_SID
        #     value: ORCL
        #   - name: ORACLE_PWD
        #     value: password
          # - name: INIT_SGA_SIZE
          #   value: 3603
          # - name: INIT_PGA_SIZE
          #   value: 3603
        ports:
        - containerPort: 1521
        # volumeMounts:
        #   - name: fcc-oracledb-config
        #     mountPath: /opt/oracle/oradata
          # - name: fcc-oracledb-startup
          #   mountPath: /docker-entrypoint-initdb.d/startup
          # - name: fcc-oracledb-setup
          #   mountPath: /docker-entrypoint-initdb.d/setup
      imagePullSecrets: 
      - name: ftb-acr-secret
      volumes:
      - name: ftb-oracledb-config
        persistentVolumeClaim:
         claimName: ftb-oracledb-config-pvc      

