apiVersion: v1
kind: PersistentVolume
metadata:
  name: fcc-pv-fccmysqldb-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: fcc-poc
    name: fcc-pvc-claim-fccmysqldb-1
  # storageClassName: my-azurefile
  azureFile:
    shareName: fcc-tomcat-test1
    secretName: fcc-afs-aks-secret
    readOnly: false
  mountOptions:
    # - dir_mode=0731
    # - file_mode=0724
    - uid=999
    - gid=999