apiVersion: v1
kind: PersistentVolume
metadata:
  name: fcc-tomcat-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  azureDisk:
    diskURI: /subscriptions/f4c6caf2-122a-491f-928a-ffa197a45fcd/resourceGroups/AZR-C21-DV-111-07-BETA/providers/Microsoft.Compute/disks/fcctomcatapp
    diskName: fcctomcatapp
    kind: Managed
    fsType: ext4
  # azureFile:
  #   shareName: test1
  #   secretName: fcc-afs-aks-secret
  #   readOnly: false
# mountOptions:
#   - uid=0
#   - gid=0
#   - dir_mode=0777
#   - file_mode=0777
#   - vers=3.0
#   - serverino
#   - mfsymlinks
#   - cache=strict
#   - actimeo=30