apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcc-tomcat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
  # volumeName: fcc-tomcat-pv