apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcc-postgresqldbpvc-claim
spec:
  resources:
    requests:
      storage: 20Gi
  storageClassName: my-azurefile
  accessModes:
    - ReadWriteMany
  volumeName: fcc-postgresqldb-pv