apiVersion: v1
kind: PersistentVolume
metadata:
  name: fcc-postgresqldb-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: fcc-poc
    name: fcc-postgresqldb-config-fccpostgresqldb-0
  # storageClassName: my-azurefile
  azureFile:
    shareName: fcc-tomcat-postgresql
    secretName: fcc-afs-aks-secret
    readOnly: false
  # mountOptions:
    # - dir_mode=0777
    # - file_mode=0777
    # - uid=1001
    # - gid=1001
  mountOptions:
    - dir_mode=0774
    - file_mode=0774
    - uid=1001
    - gid=0