kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: kubernetes.io/azure-file
# mountOptions:
#   - uid=1001
#   - gid=1001
  # - dir_mode=0750
  # - file_mode=0750
  # - vers=3.0
  # - serverino
  # - mfsymlinks
  # - cache=strict
  # - actimeo=30
parameters:
  skuName: Standard_LRS