--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: /__w/2/s/XmlToDatabase/build/../..//XmlToDatabase/db_values/init_scripts/MYSQL/mpCurrencyValues.xml
--  Ran at: 8/24/21 4:10 AM
--  Against: null@offline:mysql?changeLogFile=changelogfile_mysql.csv
--  Liquibase version: 4.3.5
--  *********************************************************************

--  Changeset __w/2/s/XmlToDatabase/build/../../XmlToDatabase/db_values/init_scripts/MYSQL/mpCurrencyValues.xml::1588865319356-1::generated
use synergie;
INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ADP', '00001', 0, 'peseta', 'penny', 'ANDORRAN PESETA', NULL, NULL, 'AD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AED', '00001', 2, 'United Arab Emirates dirhams', 'fils', 'UAE DIRHAM', NULL, NULL, 'AE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AFA', '00001', 2, 'Afghanis', 'puls', 'AFGHANI', NULL, NULL, 'AF');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AFN', '00001', 2, 'Afghani', 'pul', 'AFGHANI', NULL, NULL, 'AF');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ALL', '00001', 2, 'Albanian leke', NULL, 'ALBANIAN LEK', NULL, NULL, 'AL');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AMD', '00001', 0, 'Armenian dram', 'Luma', 'ARMENIAN DRAM', NULL, NULL, 'AM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ANG', '00001', 2, 'Netherlands Antillean guilder', 'cent', 'NETHERLANDS ANTILLES', NULL, NULL, 'AN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AOA', '00001', 2, 'Angolan kwanzas', 'cêntimos', 'ANGOLA KWANZA', NULL, NULL, 'AO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ARS', '00001', 2, 'Argentine Pesos', 'centavos', 'ARGENTINE PESO', NULL, NULL, 'AR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AUD', '00001', 2, 'Australian dollars', 'cents', 'AUSTRALIAN DOLLAR', NULL, NULL, 'AU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AWG', '00001', 2, 'Aruban florin', 'cent', 'ARUBA GUILDER', NULL, NULL, 'AW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('AZN', '00001', 2, 'Azerbaijani manat', 'Qepik', 'AZERBAIJAN NEW MANAT', NULL, NULL, 'AZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BAM', '00001', 2, 'Bosnian Convertible Marks', 'pfenigs', 'BAM', NULL, NULL, 'BA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BBD', '00001', 2, 'Barbadian dollars', 'cents', 'BARBADOS DOLLAR', NULL, NULL, 'BB');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BDT', '00001', 2, 'Bangladeshi Taka', 'poisha', 'BANGLADESHI TAKA', NULL, NULL, 'BD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BGL', '00001', 2, 'lev', 'stoinka', 'LEV', NULL, NULL, 'BG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BGN', '00001', 2, 'Bulgarian Levove', 'Stotinki', 'BULGARIAN LEV', NULL, NULL, 'BG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BHD', '00001', 3, 'Bahraini Dinars', 'fils', 'BAHRAINI DINAR', NULL, NULL, 'BH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BIF', '00001', 2, 'Burundian Francs', 'Centimes', 'BURUNDI FRANC', NULL, NULL, 'BI');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BMD', '00001', 2, 'Bermudian dollars', 'cents', 'BERMUDA DOLLAR', NULL, NULL, 'BM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BND', '00001', 2, 'Brunei dollars', 'cents', 'BRUNEI DOLLAR', NULL, NULL, 'BN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BOB', '00001', 2, 'Bolivian bolivianos', 'centavos', 'BOLIVIANO', NULL, NULL, 'BO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BRL', '00001', 2, 'Brazilian Reais', 'centavos', 'BRAZILIAN REAL', NULL, NULL, 'BR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BSD', '00001', 2, 'Bahamian Dollars', 'cents', 'BAHAMAS DOLLAR', NULL, NULL, 'BS');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BTN', '00001', 2, 'Bhutanese Ngultrum', 'Chhertum', 'BHUTAN NGULTRUM', NULL, NULL, 'BT');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BWP', '00001', 2, 'Botswana Pula', 'Thebe', 'BOTSWANESE PULA', NULL, NULL, 'BW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BYR', '00001', 0, 'Belarusian Rubles', 'Kapiejka', 'BELARUS RUBLE', NULL, NULL, 'BY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('BZD', '00001', 2, 'Belize Dollars', 'cents', 'BELIZE DOLLAR', NULL, NULL, 'BZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CAD', '00001', 2, 'Canadian dollars', 'cents', 'CANADIAN DOLLAR', NULL, NULL, 'CA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CDF', '00001', 2, 'Congolese franc', 'centime', 'CONGOLESE FRANC', NULL, NULL, 'CD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CHF', '00001', 2, 'franc', 'centime', 'SWISS FRANC', NULL, NULL, 'CH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CLP', '00001', 0, 'Chilean pesos', 'centavos', 'CHILEAN PESO', NULL, NULL, 'CL');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CNY', '00001', 2, 'renminbi', 'fen', 'YUAN RENMINBI', NULL, NULL, 'CN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('COP', '00001', 2, 'Colombian Peso', 'Centavo', 'COLOMBIAN PESO', NULL, NULL, 'CO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CRC', '00001', 2, 'Costa Rican Colon', 'Céntimo', 'COSTA RICAN COLON', NULL, NULL, 'CR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CUC', '00001', 2, 'Cuban Convertible Peso', 'Centavo Convertible', 'CUBA CONVERTIBLE PESO', NULL, NULL, 'CU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CUP', '00001', 2, 'Cuban peso', 'Centavo', 'CUBAN PESO', NULL, NULL, 'CU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CVE', '00001', 2, 'Cape Verdean Escudos', 'Centavos', 'CAPE-VERDE ESCUDO', NULL, NULL, 'CV');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('CZK', '00001', 2, 'Czech koruna', 'heller', 'CZEC KORUNA', NULL, NULL, 'CZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('DJF', '00001', 0, 'Djiboutian Franc', NULL, 'DJIBOUTI FRANC', NULL, NULL, 'DJ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('DKK', '00001', 2, 'Krone', 'ear', 'DANISH KRONE', NULL, NULL, 'DK');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('DOP', '00001', 2, 'Dominican Peso', 'Centavo', 'DOMINICAN PESO', NULL, NULL, 'DO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('DZD', '00001', 2, 'Algerian Dinars', 'centimes', 'ALGERIAN DINAR', NULL, NULL, 'DZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('EGP', '00001', 2, 'Egyptian Pound', 'Piastre', 'EGYPTIAN POUND', NULL, NULL, 'EG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ERN', '00001', 0, 'Eritrean Nakfa', NULL, 'ERITREAN NAKFA', NULL, NULL, 'ER');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ETB', '00001', 2, 'Ethiopian Birr', 'Santim', 'ETHIOPIAN BIRR', NULL, NULL, 'ET');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('EUR', '00001', 2, 'Euros', 'cents', 'EURO', NULL, NULL, 'EU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('FJD', '00001', 2, 'Fijian Dollar', 'cent', 'FIJIAN DOLLAR', NULL, NULL, 'FJ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('FKP', '00001', 2, 'Falkland Islands pound', 'penny', 'FALKLAND STERLING', NULL, NULL, 'FK');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GBP', '00001', 2, 'Pounds sterling', 'pence', 'BRITISH POUND', NULL, NULL, 'GB');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GEL', '00001', 2, 'Georgian lari', 'tetri', 'GEORGIAN LARIE', NULL, NULL, 'GE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GHS', '00001', 2, 'Ghanaian cedi', 'pesewa', 'GHANA CEDI', NULL, NULL, 'GH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GIP', '00001', 2, 'Gibraltar pound', 'penny', 'GIBRALTAR STERLING', NULL, NULL, 'GI');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GMD', '00001', 2, 'Gambian dalasi', 'butut', 'GAMBIAN DALASIE', NULL, NULL, 'GM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GNF', '00001', 2, 'Guinean franc', 'centime', 'GUINEAN FRANC', NULL, NULL, 'GN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GTQ', '00001', 2, 'Guatemalan Quetzal', 'Centavo', 'GUATEMALA QUETZAL', NULL, NULL, 'GT');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GWP', '00001', 2, 'peso', 'centavos', 'GUINEA-BISSAU PESO', NULL, NULL, 'GW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('GYD', '00001', 2, 'Guyanese dollar', 'cent', 'GUYANA DOLLAR', NULL, NULL, 'GY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('HKD', '00001', 2, 'Hong Kong dollars', 'cents', 'HONG KONG DOLLAR', NULL, NULL, 'HK');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('HNL', '00001', 2, 'Honduran lempira', 'centavo', 'HONDURAS LEMPIRA', NULL, NULL, 'HN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('HRK', '00001', 2, 'Croatian Kuna', 'lipa', 'CROATIAN KUNA', NULL, NULL, 'HR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('HTG', '00001', 2, 'Haitian gourde', 'centime', 'HAITIAN GOURD', NULL, NULL, 'HT');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('HUF', '00001', 2, 'Hungarian forint', 'fillér', 'HUNGARIAN FORINT', NULL, NULL, 'HU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('IDR', '00001', 2, 'Rupiah', 'sen', 'INDONESIAN RUPIAH', NULL, NULL, 'ID');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ILS', '00001', 2, 'Israeli Shekel', 'agorat', 'ISRAELI SHEKEL', NULL, NULL, 'IL');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('IQD', '00001', 3, 'Iraqi dinar', 'fils', 'IRAQI DINAR', NULL, NULL, 'IQ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('INR', '00001', 2, 'Indian Rupees', 'paisa', 'INDIAN RUPEE', NULL, NULL, 'IN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('IRR', '00001', 2, 'Iranian rial', 'dinar', 'IRANIAN RIAL', NULL, NULL, 'IR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ISK', '00001', 0, 'Icelandic Krona', NULL, 'ICELANDIC CROWN', NULL, NULL, 'IS');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('JEP', '00001', 2, 'Pounds sterling', 'pence', 'JERSEY POUND', NULL, NULL, 'JE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('JMD', '00001', 2, 'Jamaican Dollars', 'cents', 'JAMAICAN DOLLAR', NULL, NULL, 'JM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('JOD', '00001', 3, 'Jordanian Dinar', 'qirsh', 'JORDANIAN DIRHAM', NULL, NULL, 'JO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('JPY', '00001', 0, 'Japanese yen', 'sen', 'JAPANESE YEN', NULL, NULL, 'JP');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KES', '00001', 2, 'Kenyan Shilling', 'cent', 'KENYAN SHILLING', NULL, NULL, 'KE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KGS', '00001', 0, 'Kyrgyzstani Som', NULL, 'KIRGHIZISTAN SOM', NULL, NULL, 'KG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KHR', '00001', 2, 'Cambodian riels', 'sens', 'DEMOCRATIC KAMPUCHEA RIEL', NULL, NULL, 'KH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KMF', '00001', 2, 'Comorian franc', 'centime', 'COMORO ISLANDS FRANC', NULL, NULL, 'KM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KPW', '00001', 2, 'North Korean won', 'chon', 'NORTH KOREAN WON', NULL, NULL, 'KP');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KRW', '00001', 0, 'won', 'jeon', 'KOREAN WON', NULL, NULL, 'KR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KWD', '00001', 3, 'dinar', 'fils', 'KUWAITI DINAR', NULL, NULL, 'KW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KYD', '00001', 2, 'Cayman Islands dollars', 'cents', 'CAYMAN ISLANDS DOLLAR', NULL, NULL, 'KY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('KZT', '00001', 2, 'Kazakhstani Tenge', 'tiin', 'KAZAKHSTAN TENGUE', NULL, NULL, 'KZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LAK', '00001', 2, 'Lao kip', 'att', 'LAOS KIP', NULL, NULL, 'LA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LBP', '00001', 2, 'Lebanese pound', 'piastre', 'LEBANESE POUND', NULL, NULL, 'LB');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LKR', '00001', 2, 'rupees', 'cents', 'SRI LANKA RUPEE', NULL, NULL, 'LK');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LRD', '00001', 2, 'Liberian dollar', 'cent', 'LRD', NULL, NULL, 'LR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LSL', '00001', 2, 'Lesotho loti', 'sente', 'LIBERIAN DOLLAR', NULL, NULL, 'LS');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LTL', '00001', 2, 'Lithuanian litas', 'centas', 'LESOTHO LOTI', NULL, NULL, 'LT');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LVL', '00001', 2, 'Latvian lats', 'santims', 'LATVIAN LATS', NULL, NULL, 'LV');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('LYD', '00001', 2, 'Libyan dinar', 'dirham', 'LYBIAN DINAR', NULL, NULL, 'LY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MAD', '00001', 2, 'dirham', 'santim', 'MOROCCAN DIRHAM', NULL, NULL, 'MA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MDL', '00001', 2, 'Moldovan leu', 'ban', 'MOLDAVIAN LEU', NULL, NULL, 'MD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MGA', '00001', 2, 'Malagasy ariary', 'iraimbilanja', 'MALAGASY FRANC', NULL, NULL, 'MG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MKD', '00001', 2, 'Macedonian Denar', 'deni', 'MACEDONIAN DENAR', NULL, NULL, 'MK');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MMK', '00001', 2, 'Burmese kyat', 'pya', 'MYANMAR (BURMA) KYAT', NULL, NULL, 'MM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MNT', '00001', 2, 'Mongolian Tughrik', 'Möngö', 'MONGOLIAN TUGRIK', NULL, NULL, 'MN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MOP', '00001', 2, 'Macau Pataca', 'ho', 'MACAO PATACA', NULL, NULL, 'MO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MRO', '00001', 1, 'Mauritanian ouguiya', 'khoums', 'MAURITANIAN OUGUIYA', NULL, NULL, 'MR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MTL', '00001', 2, 'lira', 'cents', 'MALTESE LIRA', NULL, NULL, 'MT');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MUR', '00001', 2, 'rupees', 'cents', 'MAURITIUS RUPEE', NULL, NULL, 'MU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MVR', '00001', 2, 'Maldivian rufiyaa', 'iaari', 'MALDIVIAN RUFIYAA', NULL, NULL, 'MV');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MWK', '00001', 2, 'Malawian kwacha', 'tambala', 'MALAWI KWACHA', NULL, NULL, 'MW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MXN', '00001', 2, 'Mexican peso', 'centavo', 'MEXICAN PESO', NULL, NULL, 'MX');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MYR', '00001', 2, 'Malaysian ringgit', 'sen', 'MALAYSIAN RINGGIT', NULL, NULL, 'MY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('MZN', '00001', 2, 'Mozambican Metical', 'centavo', 'MOZAMBIQUE METICAL', NULL, NULL, 'MZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('NAD', '00001', 2, 'Namibian Dollar', 'cent', 'NAMIBIAN DOLLAR', NULL, NULL, 'NA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('NGN', '00001', 2, 'Naira', 'kobo', 'NIGERIAN NAIRA', NULL, NULL, 'NG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('NIO', '00001', 2, 'Nicaraguan córdoba', 'centavo', 'NICARAGUA CORDOBA ORO', NULL, NULL, 'NI');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('NOK', '00001', 2, 'Norwegian Kroner', 'ore', 'NORWEGIAN KRONE', NULL, NULL, 'NO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('NPR', '00001', 2, 'Nepalese rupee', 'paisa', 'NEPALESE ROUPIA', NULL, NULL, 'NP');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('NZD', '00001', 2, 'New Zealand dollar', 'cents', 'NEW ZEALAND DOLLAR', NULL, NULL, 'NZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('OMR', '00001', 3, 'rial', 'baisa', 'OMANI RIAL ', NULL, NULL, 'OM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PAB', '00001', 2, 'Panamanian balboa', 'Centésimo', 'PANAMA BALBOA', NULL, NULL, 'PA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PEN', '00001', 2, 'Peruvian sol', 'céntimo', 'PERUVIAN OL', NULL, NULL, 'PE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PGK', '00001', 2, 'Papua New Guinean kina', 'toea', 'PAPOUASIA NEW GUINEA KINA', NULL, NULL, 'PG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PHP', '00001', 2, 'Philippine peso', 'centimo', 'PHILIPPINE PESO', NULL, NULL, 'PH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PKR', '00001', 2, 'Pakistani rupee', 'paise', 'PAKISTAN RUPEE', NULL, NULL, 'PK');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PLN', '00001', 2, 'zloty', 'grosz', 'POLISH ZLOTY', NULL, NULL, 'PL');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('PYG', '00001', 2, 'Paraguayan guaraní', 'céntimo', 'PARAGUAYAN GUARANI', NULL, NULL, 'PY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('QAR', '00001', 2, 'riyal', 'dirham', 'QATARI RIAL', NULL, NULL, 'QA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('RON', '00001', 2, 'Romanian leu', 'ban', 'ROMANIAN NEW LEU', NULL, NULL, 'RO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('RSD', '00001', 2, 'Serbian Dinar', 'para', 'SERBIA DINAR', NULL, NULL, 'RS');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('RUB', '00001', 2, 'ruble', 'kopeyka', 'RUSSIAN RUBLE', NULL, NULL, 'RU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('RUR', '00001', 2, 'ruble', 'kopeyka', 'RUSSIAN RUBLE', NULL, NULL, 'RU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('RWF', '00001', 2, 'Rwandan franc', 'centime', 'RWANDAN FRANC', NULL, NULL, 'RW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SAR', '00001', 2, 'Saudi riyal', 'Halalah', 'SAUDI RIYAL', NULL, NULL, 'SA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SBD', '00001', 2, 'Solomon Islander Dolla', 'cent', 'SALOMON ISLANDS DOLLAR', NULL, NULL, 'SB');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SCR', '00001', 2, 'Seychellois rupee', 'cent', 'SEYCHELLES ISLANDS ROUPIA', NULL, NULL, 'SC');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SDG', '00001', 2, 'Sudanese pound', 'qirsh', 'SUDAN POUND', NULL, NULL, 'SD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SEK', '00001', 2, 'krona', 'ore', 'SWEDISH KRONA', NULL, NULL, 'SE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SGD', '00001', 2, 'Singapore dollars', 'cents', 'SINGAPORE DOLLAR', NULL, NULL, 'SG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SHP', '00001', 2, 'Saint Helena pound', 'penny', 'ST HELENA POUND', NULL, NULL, 'SH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SLL', '00001', 0, 'Sierra Leonean leone', 'cent', 'SIERRA LEONE LEONE', NULL, NULL, 'SL');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SOS', '00001', 2, 'Somali shilling', 'senti', 'SOMALIAN DOLLAR', NULL, NULL, 'SO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SRD', '00001', 2, 'Surinamese dollar', 'cent', 'SURINAME DOLLAR', NULL, NULL, 'SR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('STD', '00001', 2, 'Sao Tome and Principe dobra', 'centimo', 'SAO TOME AND PRINCIPE DOBRA', NULL, NULL, 'ST');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SVC', '00001', 2, 'Salvadoran colon', 'centavo', 'EL SALVADOR COLON', NULL, NULL, 'SV');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SYP', '00001', 2, 'Syrian pound', 'piastre', 'SYRIAN POUND', NULL, NULL, 'SY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('SZL', '00001', 2, 'Swazi lilangeni', 'cent', 'SWAZILAND LILANGENI', NULL, NULL, 'SZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('THB', '00001', 2, 'bahts', 'satang', 'THAI BAHT', NULL, NULL, 'TH');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TJS', '00001', 0, 'Tajikistani somoni', 'diram', 'TAJIK SOMONI', NULL, NULL, 'TJ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TMT', '00001', 2, 'Turkmenistan manat', 'tenge', 'TURKMENISTAN MANAT', NULL, NULL, 'TM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TND', '00001', 3, 'dinar', 'milim', 'TUNISIAN DINAR', NULL, NULL, 'TN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TOP', '00001', 2, 'Tongan Pa anga', 'seniti', 'TONGA PA ANGA', NULL, NULL, 'TO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TPE', '00001', 2, 'escudo', 'centavo', 'TIMOR ESCUDO', NULL, NULL, 'AD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TRY', '00001', 2, 'Turkish Lira', 'kurus', 'TURKISH LIRA', NULL, NULL, 'TR');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TTD', '00001', 2, 'Trinidad and Tobago dollar', 'cents', 'TRINI-TOBAGO DOLLAR', NULL, NULL, 'TP');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TWD', '00001', 2, 'New Taiwan dollar', 'cents', 'TAIWANESE DOLLAR', NULL, NULL, 'TW');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('TZS', '00001', 2, 'Tanzanian Shilling', 'cent', 'TANZANIAN SHILLING', NULL, NULL, 'TZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('UAH', '00001', 2, 'Ukrainian Hryvnia', 'Kopiyka', 'UKRAINE HRYVNA', NULL, NULL, 'UA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('UGX', '00001', 2, 'Ugandan shilling', 'cent', 'UGANDAN SHILLING', NULL, NULL, 'UG');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('USD', '00001', 2, 'United States Dollars', 'cents', 'UNITED STATES DOLLAR', NULL, NULL, 'US');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('UYU', '00001', 2, 'Uruguayan Peso', 'Centésimo', 'URUGUAYAN PESO', NULL, NULL, 'UY');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('UZS', '00001', 2, 'Uzbekistani som', 'tiyin', 'UZBEKISTAN SOM', NULL, NULL, 'UZ');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('VEF', '00001', 2, 'Venezuelan Bolívar', 'centimo', 'VENEZUELA BOLIVAR FUERTE', NULL, NULL, 'VE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('VND', '00001', 0, 'Vietnamese Dong', 'hao', 'VIETNAMESE DONG', NULL, NULL, 'VN');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('VUV', '00001', 0, 'Vanuatu vatu', NULL, 'VANUATU VATU', NULL, NULL, 'VU');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('WST', '00001', 2, 'Samoan tala', 'sene', 'SAMOA TALA', NULL, NULL, 'WS');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('XAF', '00001', 2, 'Francs', 'centimes', 'CFA BEAC FRANC', NULL, NULL, 'XA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('XCD', '00001', 2, 'East Caribbean Dollar', 'cent', 'EAST CARIBBEAN DOLLAR', NULL, NULL, 'XC');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('XDR', '00001', 0, 'Special drawing rights', NULL, 'SPECIAL DRAWING RIGHTS', NULL, NULL, 'XD');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('XOF', '00001', 2, 'Francs', 'Centimes', 'Franc CFA BCEAO', NULL, NULL, 'XO');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('XPF', '00001', 2, 'CFP Franc', 'centime', 'CFP FRANC', NULL, NULL, 'XP');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('YER', '00001', 1, 'Yemeni Rial', 'fils', 'YEMEN RIAL', NULL, NULL, 'YE');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ZAR', '00001', 2, 'South African Rand', 'cents', 'SOUTH AFRICAN RAND', NULL, NULL, 'ZA');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ZMW', '00001', 2, 'Zambian Kwacha', 'ngwee', 'ZAMBIAN KWACHA', NULL, NULL, 'ZM');

INSERT INTO GTP_MASTER_CURRENCY (ISO_CODE, BRCH_CODE, DECIMAL_NUMBER, MAJOR_NAME, MINOR_NAME, NAME, PARITY, ROUND_CODE, PRINC_COUNTRY_CODE) VALUES ('ZWD', '00001', 2, 'Zimbabwean Dollar', 'cent', 'ZIMBABWE DOLLAR', NULL, NULL, 'ZW');

