apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcc-mssql2019-claim
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  volumeName: fcc-mssql2019-volume
