apiVersion: v1
kind: PersistentVolume
metadata:
  name: fcc-appdata-volume
spec:
  capacity:
    storage: 10Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: fcc-afs-aks-secret
    shareName: fcc-mssql-2019-aks/fcctomcatappdatamssql2019/appdata
    readOnly: false
#    type: Directory
#  mountOptions:
#  - dir_mode=0777
#  - file_mode=0777
#  - uid=postgres
#  - gid=postgres
#  - mfsymlinks
#  - nobrl
  storageClassName: azurefile
#  persistentVolumeReclaimPolicy: Retain
