apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    version: 1.0.0
  name: {{ .Values.fccmysqldb_deployment.name }}
  namespace: fcc-poc
  labels:
    app: {{ .Values.fccmysqldb_deployment.labels.app }}
    io.service: {{ .Values.fccmysqldb_deployment.labels.io_service }}
spec:
  replicas: 1
  serviceName: {{ .Values.fccmysqldb_service.name}}
  # podManagementPolicy: Parallel
  selector:
    matchLabels:
      io.service: {{ .Values.fccmysqldb_deployment.labels.io_service }}
  updateStrategy:
    type: {{ .Values.fccsqldb_replicaset.strategytype }}
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.fccmysqldb_deployment.labels.app }}
        io.service: {{ .Values.fccmysqldb_deployment.labels.io_service }}
    spec:
      containers:      
      - name: {{ .Values.fccmysqldb_pod.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: {{ .Values.fccmysqldb_pod.env.name1 }}
          value: {{ .Values.fccmysqldb_pod.env.value1 }}
        - name: {{ .Values.fccmysqldb_pod.env.name2 }}
          value: {{ .Values.fccmysqldb_pod.env.value2 }}
        ports:
        - containerPort: {{ .Values.fccmysqldb_service.containerPort}}
          name: {{ .Values.fccmysqldb_service.portname}}
        volumeMounts:
          # - name: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_config.name }}
          #   mountPath: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_config.mountPath }}
          - name: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_dbscript.name }}
            mountPath: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_dbscript.mountPath }}
        args: 
        - --lower_case_table_names=1
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      hostname: {{ .Values.fccmysqldb_pod.hostname }}
      volumes:
        - name: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_dbscript.name }}
          azureFile:
            shareName: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_dbscript.azureshare }}
            secretName: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_dbscript.afs_secret }}
            readOnly: false
  # volumeClaimTemplates:
  #   - metadata:
  #       name: {{ .Values.fccmysqldb_pod.volumeMounts.mysql_config.name }}
  #     spec:
  #       accessModes:
  #         - "ReadWriteMany"
  #       resources:
  #         requests:
  #           storage: 10Gi

            